export enum Global {
	ACCESS_APP,
	VIEW_ALL_USERS,
	VIEW_ALL_EVENTS,
	VIEW_ALL_INVITATIONS,
	VIEW_ALL_LOCATIONS,
	VIEW_ALL_PERMISSIONS,
	VIEW_ALL_RESPONSES,
	VIEW_LOG,
	EDIT_ALL_USERS,
	EDIT_ALL_EVENTS,
	EDIT_ALL_INVITATIONS,
	EDIT_ALL_LOCATIONS,
	EDIT_ALL_PERMISSIONS,
	EDIT_ALL_RESPONSES,
	ADMIN_EVENT,
	ADMIN_LOCATION,
	ADMIN_USER,
	ADMIN_ALL,
}

export enum Event {
	VIEW,
	EDIT_DATE,
	EDIT_LOCATION,
	EDIT_INVITATION,
	EDIT_DETAILS,
	EDIT_ALL,
}

export default { Global, Event };
