<?php
$DB_SERVER = $_ENV['DV_SERVER'];
$DB_USER = $_ENV['DB_USER'];
$DB_PASSWORD = $_ENV['DB_PASSWORD'];
$DB_DATABASE = $_ENV['DB_DATABASE'];

$WEBSITE_NAME = $_ENV['WEBSITE_NAME'];

$DISCORD_SECRET = $_ENV['DISCORD_SECRET'];
$DISCORD_ID = $_ENV['DISCORD_ID'];

